<?php

/**
 * PluginaEntityToEntityTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaEntityToEntityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaEntityToEntityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaEntityToEntity');
    }
}