<?php

/**
 * PluginaEntityToBlogItemTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaEntityToBlogItemTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaEntityToBlogItemTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaEntityToBlogItem');
    }
}