<?php

/**
 * PluginaEntityTable
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginaEntityTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginaEntityTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginaEntity');
    }

    public function findAllSorted()
    {
      return $this->findAllSortedBody(array('hydrate' => Doctrine_Core::HYDRATE_RECORD));
    }

    public function findAllSortedBody($options = array())
    {
      $hydrate = isset($options['hydrate']) ? $options['hydrate'] : Doctrine_Core::HYDRATE_RECORD;
      $query = $this->createQuery('e');
      $this->addOrderBy($query);
      return $query->execute(array(), $hydrate);
    }

    public function addOrderBy($query)
    {
      $query->orderBy('e.name');
    }

    public function findAllSortedArray()
    {
      return $this->findAllSortedBody(array('hydrate' => Doctrine_Core::HYDRATE_ARRAY));
    }

}
