generator:
  class: sfDoctrineGenerator
  param:
    model_class:           aEntity
    theme:                 aAdmin
    non_verbose_templates: true
    with_show:             false
    singular:              entity
    plural:                entities
    route_prefix:          a_entity_admin
    with_doctrine_route:   true
    actions_base_class:    sfActions

    config:
      actions: ~
      fields:  ~
      list:
        table_method: doSelectJoinArea
      filter:  ~
      form:    ~
      edit:    ~
      new:     ~
